name: project_tweety
description: "A playground app to try out ideas that we aren't implementing at work or I would like to implement at work."
publish_to: 'none'

version: 0.2.0

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.38.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  equatable: ^2.0.0
  flutter_bloc: ^9.0.0
  get_it: ^9.2.0
  google_fonts: 6.3.0
  http: ^1.0.0
  injectable: ^2.7.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: any
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true